### ISSUE TITLE
backports-source-v5.10-rc6-1.tar.xz] Error 128

### ISSUE THREAD

**Issue by runner097** [hzyitc/openwrt-redmi-ax3000#11]
Checking out files from the git repository...
Cloning into 'backports-source-v5.10-rc6-1'...
fatal: unable to connect to git.kernel.org:
git.kernel.org[0: 145.40.68.75]: errno=Connection refused
git.kernel.org[1: 2604:1380:4601:e00::1]: errno=Network is unreachable

make[3]: *** [Makefile:511: /home/x/openwrt/openwrt-redmi-ax3000-ipq50xx-mainline-kernel-5.4-openwrt-21.02-qsdk-wifi-11.5.05.841.1029/dl/backports-source-v5.10-rc6-1.tar.xz] Error 128

**Comment by hzyitc** [comment]
```
fatal: unable to connect to git.kernel.org:
git.kernel.org[0: 145.40.68.75]: errno=Connection refused
git.kernel.org[1: 2604:1380:4601:e00::1]: errno=Network is unreachable
```

网络问题
