### ISSUE TITLE
重启后不同vlan被dhcp分配ip问题？

### ISSUE THREAD

**Issue by yfan99** [hzyitc/openwrt-redmi-ax3000#14]
我为eth0划分了两个vlan，一个作为lan一个用来看iptv。我的iptv是使用dhcp方式获取的ip，lan使用的openwrt自带的dhcp分配ip。但是当我重启之后lan下的有线设备会获取到iptv的ip，需要手动重启接口才能正常获取ip。

**Comment by hzyitc** [comment]
怎么接线的?

u-boot开机时会划分默认vlan。就是wan一个，lan一个。启动后才能应用系统的vlan。

**Comment by yfan99** [comment]
我的VLAN配置如下
![QQ截图20230421235256](https://user-images.githubusercontent.com/36776235/233681118-7b800602-68d0-4cb7-b444-6565645f4d29.png)
![QQ截图20230421235345](https://user-images.githubusercontent.com/36776235/233683833-8e1e2a25-976c-4d59-af21-c79113d9696e.png)

我划分了一个vlan3配合udpxy看iptv 我的iptv使用的dhcp
当路由器重启之后 两个vlan1下的有线设备被iptv的dhcp分配了ip
![QQ截图20230421235908](https://user-images.githubusercontent.com/36776235/233682449-dcbec9b0-303e-4ce1-a716-d9a2c6f53011.png)
![QQ截图20230422000632](https://user-images.githubusercontent.com/36776235/233683587-63a491a0-0416-44f9-bef5-b7d092c994aa.png)
每次需要重启接口后才获取正常的由路由DHCP分配的IP网段192.168.0.x
目前我把所有有线设备配置静态ip来解决的此问题

**Comment by hzyitc** [comment]
两个解决方案：
- 重新编译`u-boot`。`u-boot`期间，禁止交换机端口间通讯。
- 系统启动后重启所有。即让所有端口下线，让对端识别到断开，后重上线。

暂时不确定别的target会不会在启动后重启所有端口。
