### ISSUE TITLE
添加 vnstat2  后编译报错 ld: libwebp.so: undefined reference to xxx

### ISSUE THREAD

**Issue by IITII** [hzyitc/openwrt-redmi-ax3000#19]
设备: CR8806 命令: `make -j1 V=sc`
日志:
[op.log](https://github.com/hzyitc/openwrt-redmi-ax3000/files/11493931/op.log)

<img width="1007" alt="image" src="https://github.com/hzyitc/openwrt-redmi-ax3000/assets/33705067/282cd115-7db5-4416-84ac-5d997433e9f4">

**Comment by hzyitc** [comment]
第三方包?

这是那个包的问题。

**Comment by IITII** [comment]
不知道是不是第三包。 我是在 meunconfig 里面的 luci -> Applications 下面选的 luci-app-vnstat2. 这个 vnstat2 的 makefile 里面依赖了 libgd。截图里面的是 libgd 编译的时候报的错。上面 op.log 有全部的日志。

**Comment by IITII** [comment]
![image](https://github.com/hzyitc/openwrt-redmi-ax3000/assets/33705067/d71d727f-4510-425e-be20-4f3148d60807)

**Comment by hzyitc** [comment]
目前看大概率是上游的问题，最新版可以直接opkg install了。直接用上游的源安装就行。
