### ISSUE TITLE
为什么我通过 opkg 安装的命令会提示 not found

### ISSUE THREAD

**Issue by IITII** [hzyitc/openwrt-redmi-ax3000#22]
* 以 frpc, frps 为例. frpc 是我直接编译进去的, frps 是我通过 opkg install 安装的
* 从下图可以看到, frps 已安装并且确实是有可执行文件的也在 PATH 下面. 但是实际上执行 frps 提示找不到
* frpc 倒是直接能找到.

```
root@OpenWrt:/etc/frp/frps.d# echo $PATH
/usr/sbin:/usr/bin:/sbin:/bin
root@OpenWrt:/etc/frp/frps.d#
```

![image](https://github.com/hzyitc/openwrt-redmi-ax3000/assets/33705067/152d68b0-17c3-400d-a87b-165b92d3dcd7)

**Comment by hzyitc** [comment]
老版本我忘记指定`CPU_SUBTYPE`了，opkg里面的链接是错的。要用`arm_cortex-a7_neon-vfpv4`而不是`arm_cortex-a7`。

新版已经修复。
