### ISSUE TITLE
[Feature Request] Add nat fullcone support

### ISSUE THREAD

**Issue by baysonfox** [hzyitc/openwrt-redmi-ax3000#26]
如题，希望能支持下，提升联机游戏时的体验。
（可参考[https://github.com/LGA1150/openwrt-fullconenat](https://github.com/LGA1150/openwrt-fullconenat)）

**Comment by hzyitc** [comment]
自行编译下吧，我仓库里面就不引入第三方包了。

晚点我把生成SDK给加上。
