### ISSUE TITLE
some qsdk kmod packages are not compiled and actually empty

### ISSUE THREAD

**Issue by Arnie97** [hzyitc/openwrt-redmi-ax3000#28]
This issue only affects the `ipq50xx-qsdk-kernel-5.4-openwrt-21.02-qsdk-11.5.05.841.1029` variant.  A heuristic approach to find the problematic packages would be: filtering packages whose size <1,200 bytes, e.g.

```sh
$ URL=https://hzyitc.github.io/openwrt-redmi-ax3000/ipq50xx-qsdk-kernel-5.4-openwrt-21.02-qsdk-11.5.05.841.1029/ci-20230629-173133-5b10c505/kmod-wireguard_5.4-qsdk-11.5.0.5-1_arm_cortex-a7_neon-vfpv4.ipk

$ curl -sLI $URL | grep -i length
content-length: 1168

$ curl -sL  $URL | tar xzO ./data.tar.gz | tar tz
./
```

**Comment by hzyitc** [comment]
`wireguard` was introduced in linux-v5.6. `Openwrt` backported it to v5.4 while `QSDK` didn't.
