### ISSUE TITLE
Reset按钮

### ISSUE THREAD

**Issue by Enignna** [hzyitc/openwrt-redmi-ax3000#29]
感谢您的奉献！我想问一下刷了这个固件之后还可以通过reset按钮恢复刚刷完机的状态吗？如果可以的话，应该怎样操作呢

**Comment by uvswifft** [comment]
reset用不了，至少我不管是刚插电时捅py还是启动一段时间后捅都没用，这样导致手残瞎改配置之后只能拆机ttl刷机。。。
如果你刷了不死uboot，倒是可以重新刷系统，但非原生boot又导致没办法web升级。。。

**Comment by uvswifft** [comment]
@hzyitc 能不能支持一下reset按键重置系统，虽然现在原生boot可以通过ab分区实现不死，但遇上系统设置错误导致连不进去，而系统又正常运行没法切换另一个分区，就只能ttl解决。。。，虽然刷不死boot可以救机，但web升级就用不了了。

**Comment by hzyitc** [comment]
忘记加`kmod-gpio-button-hotplug`这个包了。下个版本更新
