### ISSUE TITLE
Can't interrupt the U-boot

### ISSUE THREAD

**Issue by ohn0n0n0** [hzyitc/openwrt-redmi-ax3000#3]
i'm stuck on step 7. Send any key stroke to UART to interrupt the U-boot.

it shows bootwait is on, bootdelay=2. but i can't send anything to uart. my uart usb work normal with another router.
![image](https://user-images.githubusercontent.com/6015976/209336521-22354936-518f-4ea6-8c02-a62d20bb5d01.png)

**Comment by hzyitc** [comment]
Please make sure you connect to RX instand of VCC. Both of them are 1.8V.

**Comment by ohn0n0n0** [comment]
![z3993517236099_020f603cb48eea7c7b20d7d70a1ae2bb](https://user-images.githubusercontent.com/6015976/209680848-a97de0d4-f78d-4f0b-a234-ed2ab8170df7.jpg)
Is this right?

**Comment by hzyitc** [comment]
Corrent for CR8806. For AX3000, I'm not sure. Because I don't have one.

**Comment by ohn0n0n0** [comment]
> Corrent for CR8806. For AX3000, I'm not sure. Because I don't have one.

somehow i still can't interrupt the U-boot.
i have cr8806 too. what type of usb to ttl are you using? i'm using cp2102.

**Comment by hzyitc** [comment]
FT4232. Really expensive.

But i also try CH340. It works.

**Comment by hzyitc** [comment]
You can try to disconnect the RX. And use something to short RX and GND to interrupt

**Comment by ohn0n0n0** [comment]
> FT4232. Really expensive.
> 
> But i also try CH340. It works.

I bought a ch340g last night and it works. You just saved me a lot of time.

**Comment by hzyitc** [comment]
When I use STC microcontroller, CP2102 sometime fail to burn. CH340 always work well. Don't known why. But I never use it anymore.

**Comment by cyy53589** [comment]
> ![z3993517236099_020f603cb48eea7c7b20d7d70a1ae2bb](https://user-images.githubusercontent.com/6015976/209680848-a97de0d4-f78d-4f0b-a234-ed2ab8170df7.jpg) Is this right?

Hi, may I ask how do you connect pins to the UART hole? Using soldering or articulated arm or something ... ?
I hold pins swingingly and connection isn't steady.

@hzyitc @ohn0n0n0

**Comment by ohn0n0n0** [comment]
> > ![z3993517236099_020f603cb48eea7c7b20d7d70a1ae2bb](https://user-images.githubusercontent.com/6015976/209680848-a97de0d4-f78d-4f0b-a234-ed2ab8170df7.jpg) Is this right?
> 
> Hi, may I ask how do you connect pins to the UART hole? Using soldering or articulated arm or something ... ? I hold pins swingingly and connection isn't steady.
> 
> @hzyitc @ohn0n0n0
![1BA05898-96E8-4F03-984F-EA783F475D44L0001 png png](https://user-images.githubusercontent.com/6015976/215332256-bcea3a77-e29c-4c40-a566-1af6e66b0c83.jpg)

no need to soldering or articulated. 
![DC5A9F9C-910A-486A-ABA5-A28B82549524L0001 png png](https://user-images.githubusercontent.com/6015976/215332261-2d355035-55d5-4e66-8e4d-6745baa6b93b.jpg)

**Comment by cyy5358** [comment]
> swingingly

I see. cool

**Comment by cyy53589** [comment]
> > > ![z3993517236099_020f603cb48eea7c7b20d7d70a1ae2bb](https://user-images.githubusercontent.com/6015976/209680848-a97de0d4-f78d-4f0b-a234-ed2ab8170df7.jpg) Is this right?
> > 
> > 
> > Hi, may I ask how do you connect pins to the UART hole? Using soldering or articulated arm or something ... ? I hold pins swingingly and connection isn't steady.
> > @hzyitc @ohn0n0n0
> > ![1BA05898-96E8-4F03-984F-EA783F475D44L0001 png png](https://user-images.githubusercontent.com/6015976/215332256-bcea3a77-e29c-4c40-a566-1af6e66b0c83.jpg)
> 
> no need to soldering or articulated. ![DC5A9F9C-910A-486A-ABA5-A28B82549524L0001 png png](https://user-images.githubusercontent.com/6015976/215332261-2d355035-55d5-4e66-8e4d-6745baa6b93b.jpg)

I see. cool!
