### ISSUE TITLE
在最新的releases中，并没有找到ubi文件

### ISSUE THREAD

**Issue by XiaoTong6666** [hzyitc/openwrt-redmi-ax3000#30]
您好大佬，就是我在sha256上写到了
openwrt-ipq50xx-arm-redmi_ax3000-squashfs-nand-factory.ubi: ab4b6ef5f37b2f477bb0811f1aad6ff13ba78763a20c5f7fd90789bedc3305bf
但是下面的包却没有openwrt-ipq50xx-arm-redmi_ax3000-squashfs-nand-factory.ubi，请问下有什么办法才能直接下载嘛

**Comment by hzyitc** [comment]
emmm，有点神奇，看action那边是成功上传的，不知道为啥丢文件了。

我传新版了，等新的CI完成吧。

**Comment by XiaoTong6666** [comment]
ok，感谢大佬！
