### ISSUE TITLE
奇奇怪怪的 Commit 时间

### ISSUE THREAD

**Issue by baysonfox** [hzyitc/openwrt-redmi-ax3000#31]
![CleanShot 2023-07-16 at 23 09 24](https://github.com/hzyitc/openwrt-redmi-ax3000/assets/23008133/152377e4-1c1f-4fa9-b64b-2a4340af0150)
不知道是什么原因 即使是本来就存在的 commit, 时间都突然被更新了

**Comment by hzyitc** [comment]
当初为了能够提交PR，所以选择了rebase，并直接修改历史commit的。

当然这样会丢失掉我bug的修复记录，但一直留着修bug的记录的话，不便于我以后提交PR。所以暂时就这样了，之后可能会考虑把commit拆分得更细。
