### ISSUE TITLE
最新的openwrt23.05的wifi速度有问题

### ISSUE THREAD

**Issue by uvswifft** [hzyitc/openwrt-redmi-ax3000#37]
wifi上行跑不满千兆端口速度，封顶大概700-800Mbps，但严重的是wifi下行只能跑500Mbps，很稳定的500Mbps，多次测速偏差很小。

**Comment by hzyitc** [comment]
README写了，5.15的WiFi没有NSS offload，走CPU的，你可以看看CPU是不是满的。

要NSS offload请使用其他分支。

**Comment by Kissycat** [comment]
> README写了，5.15的WiFi没有NSS offload，走CPU的，你可以看看CPU是不是满的。

借地问一下，如果把ax3000作AP用的话，把四个网口加到eth0或者eth1所在的vlan会有区别嘛？
我现在都加在同eth1的vlan，也是只能跑500M，而且连接ax3000无线信号的设备互相无法通讯...

**Comment by hzyitc** [comment]
> 把四个网口加到eth0或者eth1所在的vlan会有区别嘛？

基本没有，甚至你可以不用vlan

> 而且连接ax3000无线信号的设备互相无法通讯

#53
