### ISSUE TITLE
AX3000 Is functional + Rebase against upstream?

### ISSUE THREAD

**Issue by edrikk** [hzyitc/openwrt-redmi-ax3000#39]
Hi,
I can confirm that the installation procedure works works for the AX3000, and that all appears functional (with limited testing).
Main page table can be updated.

As a secondary item, can the repo be updated against latest upstream 23.05?

**Comment by hzyitc** [comment]
> Hi, I can confirm that the installation procedure works works for the AX3000, and that all appears functional (with limited testing). Main page table can be updated.

Greet

> 
> As a secondary item, can the repo be updated against latest upstream 23.05?

TODO. Need some tests.
