### ISSUE TITLE
cr8808 fireware problem

### ISSUE THREAD

**Issue by NakanoSanku** [hzyitc/openwrt-redmi-ax3000#4]
cr8808 
produced in 2021 use 6.2.12
produced in 2022 use 6.2.18
![eaf67ecbecf64b218fbffe0a9c44cb6a.jpeg](https://user-images.githubusercontent.com/96334375/211223927-f0f69091-4ca3-492e-88d8-f5145eec22a3.jpeg)
Because the amplifier they use has been changed
I tried to grab bags with violence，Unfortunately, its naming format seems very unique，Ihope to give you some help

**Comment by NakanoSanku** [comment]
- [x] 6.2.18~cr8806
- [x] 6.2.12~ax3000

**Comment by hzyitc** [comment]
There is no firmware for CR8808 in Xiaomi CDN. So what we can do is just to wait for the first upgrade.

**Comment by NakanoSanku** [comment]
> There is no firmware for CR8808 in Xiaomi CDN. So what we can do is just to wait for the first upgrade.

No！I seem already solve this problem，use [miwifi flash tool](https://bigota.miwifi.com/xiaoqiang/tools/MIWIFIRepairTool.x86.zip) flash cr8806 fireware ！but must sure your cr8808 fireware version is 6.2.18 ，if not you need flash ax3000 fireware![Screenshot_2023-01-09-15-00-07-583_com.android.browser-edit.jpg](https://user-images.githubusercontent.com/96334375/211255269-0a1d9b9d-6dda-40ea-ae0d-a16cbe1f3041.jpg)

**Comment by hzyitc** [comment]
I check the uboot of CR8808 again. And yes, it use the same platform magic as CR8806. I will update the README. Thank you.

**Comment by HapiLemon** [comment]
@hzyitc 
@NakanoSanku 
BTW, I have tried flashing firmware of CR8809 to my CR8808 and it works well.
