### ISSUE TITLE
ipq50xx-qsdk-kernel-5.4-openwrt-21.02-qsdk-11.5.05.841.1029分支编译一直在mac80211报错

### ISSUE THREAD

**Issue by homeassistad** [hzyitc/openwrt-redmi-ax3000#44]
小白编译，需要nss加速选择了ipq50xx-qsdk-kernel-5.4-openwrt-21.02-qsdk-11.5.05.841.1029分支，看有issues说关闭debug就能编译成功了，相关改动已经合并到主线了，但是这个分支我还是一直报错，请问怎么关闭debug

**Comment by hzyitc** [comment]
#16

**Comment by homeassistad** [comment]
就是看到这个issues问怎么关debug啊

**Comment by hzyitc** [comment]
一般都是在拉取ath分支时失败的，你直接用生成好的backports文件吧。

如果不是这个错误的话，贴日志。

**Comment by homeassistad** [comment]
重新拉库后选择ipq50xx架构make -j1 V=s编译成功，好像之前都是选择了64位系统编译，不过能编译出来就不理这些了，仅供参考

**Comment by Cathgao** [comment]
修改 `package/kernel/mac80211/Makefile` ，在EXTRA_CFLAGS=这一行的双引号里面添加 `-Wno-error=incompatible-pointer-types` 即可编译64bit系统
