### ISSUE TITLE
最新的5.15内核的23.05版本降网速

### ISSUE THREAD

**Issue by yangtseJin** [hzyitc/openwrt-redmi-ax3000#52]
下载编译了5.15内核的23.05版本固件后，我1000M的网，不管是有线还是无线，都只能跑100-200Mbs的速度

是驱动的问题吗？我的有线和无线的驱动都是用默认的，还需要添加其他的吗？

**Comment by yangtseJin** [comment]
我刷了作者发布的5.15内核的ubi固件，结果还是一样，只能跑200M左右，这是什么问题，大家有遇到过吗？

**Comment by hzyitc** [comment]
#37
