### ISSUE TITLE
upnp无法使用

### ISSUE THREAD

**Issue by kettly1260** [hzyitc/openwrt-redmi-ax3000#56]
安装upnp插件之后upnp依旧无法使用，查看配置应该是正确的，不知道确实了什么服务

**Comment by kettly1260** [comment]
此外，路由器下面的子设备都没办法互相访问

**Comment by IITII** [comment]
自己问题吧, 我目前是正常使用的
https://github.com/IITII/openwrt-redmi-ax3000
https://iitii.github.io/2023/06/07/1/

**Comment by kettly1260** [comment]
> 自己问题吧，我目前是正常使用的 [https://github.com/IITII/openwrt-redmi-ax3000 ](https://github.com/IITII/openwrt-redmi-ax3000) https://iitii.github.io/2023/06/07/1/

我换了其他固件没有这个问题，自己编译的upnp倒是没问题，但是下面的设备依旧无法互相访问

**Comment by hzyitc** [comment]
哪个分支？

**Comment by hzyitc** [comment]
> 但是下面的设备依旧无法互相访问

#53
