### ISSUE TITLE
可以分享一下ax3000的.config吗

### ISSUE THREAD

**Issue by hchyhchyxh** [hzyitc/openwrt-redmi-ax3000#57]
如题。 总感觉我配置的.config有点问题。希望作者可以分享一下编译的.config参考一下。

**Comment by hzyitc** [comment]
https://github.com/hzyitc/openwrt-redmi-ax3000/blob/cc251495d17cdfdbffa047c210c67a79932cc451/.github/workflows/ci.yml#L40-L54

**Comment by fly263** [comment]
使用这个.config文件，在编译时会弹出配置窗口，不做修改保存后编译成功，但是刷机后进不了路由器后台，能访问192.168.1.1，跳转luci失败。

如果直接退出配置窗口，无法编译，报错如下：

> Your configuration changes were NOT saved.
> 
> make[2]: Leaving directory '/home/user/openwrt-23.05'
> /home/user/openwrt-23.05/include/kernel-version.mk:11: *** Missing kernel version/hash file for . Please create /home/user/openwrt-23.05/include/kernel-.  Stop.
> time: target/linux/prereq#0.00#0.00#0.03
>     ERROR: target/linux failed to build.
> make[3]: *** [target/Makefile:32: target/linux/prereq] Error 1
> make[2]: *** [target/Makefile:24: /home/user/openwrt-23.05/staging_dir/target-_/stamp/.target_prereq] Error 2
> make[1]: *** [/home/user/openwrt-23.05/include/toplevel.mk:210: prereq] Error 2
> make: *** [/home/user/openwrt-23.05/include/toplevel.mk:230: world] Error 2

> [openwrt-redmi-ax3000/.github/workflows/ci.yml](https://github.com/hzyitc/openwrt-redmi-ax3000/blob/cc251495d17cdfdbffa047c210c67a79932cc451/.github/workflows/ci.yml#L40-L54)
> 
> Lines 40 to 54 in [cc25149](/hzyitc/openwrt-redmi-ax3000/commit/cc251495d17cdfdbffa047c210c67a79932cc451)
> 
>            cat <<EOF | sed -E 's/^  //' >.config 
>              CONFIG_TARGET_ipq50xx=y 
>              CONFIG_TARGET_ipq50xx_arm=y 
>              CONFIG_TARGET_ipq50xx_arm_DEVICE_redmi_ax3000=y 
>   
>              CONFIG_IB=y 
>              # CONFIG_IB_STANDALONE is not set 
>              CONFIG_SDK=y 
>              CONFIG_MAKE_TOOLCHAIN=y 
>   
>              CONFIG_ALL_NONSHARED=y 
>              CONFIG_REPRODUCIBLE_DEBUG_INFO=y 
>   
>              CONFIG_PACKAGE_luci=y 
>            EOF

**Comment by fly263** [comment]
进ssh安装luci包后可以进后台。
