### ISSUE TITLE
802.11k and 802.11v issues.

### ISSUE THREAD

**Issue by ohn0n0n0** [hzyitc/openwrt-redmi-ax3000#6]
i try to enable 802.11k and 802.11v for band-steering. >https://openwrt.org/docs/guide-user/network/wifi/usteer.

i install wpad full ([wpad-wolfssl](https://openwrt.org/packages/pkgdata/wpad-wolfssl) or [wpad-openssl](https://openwrt.org/packages/pkgdata/wpad-openssl))

when i add there line into /etc/config/wireless. the radio down.

option bss_transition '1'
option wnm_sleep_mode '1'
option time_advertisement '2'
option time_zone 'GMT0'
option ieee80211k '1'
option rrm_neighbor_report '1'
option rrm_beacon_report '1'

![image](https://user-images.githubusercontent.com/6015976/215333772-18ede312-0fa6-4999-ac92-bff05b834570.png)

system log:

Sun Jan 29 14:38:56 2023 daemon.notice netifd: radio0 (5180): Command failed: Request timed out
Sun Jan 29 14:38:56 2023 daemon.notice netifd: radio0 (5180): Command failed: Not found
Sun Jan 29 14:38:56 2023 daemon.notice netifd: radio0 (5180): Device setup failed: HOSTAPD_START_FAILED
Sun Jan 29 14:38:56 2023 daemon.notice netifd: Wireless device 'radio0' set retry=0
Sun Jan 29 14:38:56 2023 daemon.crit netifd: Wireless device 'radio0' setup failed, retry=0
Sun Jan 29 14:38:56 2023 daemon.notice netifd: Wireless device 'radio0' is now down

**Comment by ohn0n0n0** [comment]
i flash old version and 802.11k and 802.11v work well.
[openwrt-ipq50xx-generic-redmi_ax3000-squashfs-nand-factory.zip](https://github.com/hzyitc/openwrt-redmi-ax3000/files/10549074/openwrt-ipq50xx-generic-redmi_ax3000-squashfs-nand-factory.zip)

**Comment by hzyitc** [comment]
It seem like that this issue don't exist now?

**Comment by ohn0n0n0** [comment]
> It seem like that this issue don't exist now?

with lastest version i thinks it working now.
