### ISSUE TITLE
编译告警

### ISSUE THREAD

**Issue by chenghj87** [hzyitc/openwrt-redmi-ax3000#66]
自己编译的时候碰到下面3个告警，要怎么修复呢
WARNING: Makefile 'package/kernel/qca/qca-nss-clients/Makefile' has a build dependency on 'kmod-qca-nss-crypto', which does not exist
WARNING: Makefile 'package/kernel/qca/qca-nss-drv/Makefile' has a dependency on 'kmod-qca-nss-gmac', which does not exist
WARNING: Makefile 'package/kernel/qca/qca-ssdk/Makefile' has a dependency on 'kmod-qca-rfs', which does not exist

**Comment by hzyitc** [comment]
忽略即可。
