### ISSUE TITLE
网速问题无法突破200Mbps

### ISSUE THREAD

**Issue by okami-chen** [hzyitc/openwrt-redmi-ax3000#76]
电脑连接路由器发现协商是100Mbps，通过执行下面命令将协商修改为1000Mbps
```
ethtool eth0
ethtool -s eth0 speed 1000 duplex full autoneg on
```
重启路由器协商变成1000Mbps了，但是网速还是无法突破200Mbps（无线也不行），宽带是500Mbps，将接入路由器的网线直接插入电脑可以跑满500Mbps，

**Comment by easyatm** [comment]
你用的是最新的包吧,最新的那个是cpu nat
去下后面第一个带qsdk的版本

**Comment by hzyitc** [comment]
#37
