### ISSUE TITLE
Missing some kmod files (depended by qca-nss) when compiling the firmware

### ISSUE THREAD

**Issue by shinwa** [hzyitc/openwrt-redmi-ax3000#8]
Followed the instruction, when do 'make download -j1', show lots of error messages related to qca-nss module.
`WARNING: Makefile 'package/kernel/qca/qca-nss-clients/Makefile' has a dependency on 'kmod-qca-nss-cfi-cryptoapi', which does not exist
WARNING: Makefile 'package/kernel/qca/qca-nss-clients/Makefile' has a dependency on 'kmod-qca-nss-cfi-cryptoapi', which does not exist
WARNING: Makefile 'package/kernel/qca/qca-nss-clients/Makefile' has a dependency on 'kmod-qca-nss-cfi-ocf', which does not exist
WARNING: Makefile 'package/kernel/qca/qca-nss-clients/Makefile' has a dependency on 'kmod-qca-nss-cfi-ocf', which does not exist
WARNING: Makefile 'package/kernel/qca/qca-nss-clients/Makefile' has a dependency on 'kmod-qca-ovsmgr', which does not exist
WARNING: Makefile 'package/kernel/qca/qca-nss-clients/Makefile' has a dependency on 'kmod-qca-nss-cfi-cryptoapi', which does not exist
WARNING: Makefile 'package/kernel/qca/qca-nss-clients/Makefile' has a dependency on 'kmod-qca-nss-cfi-cryptoapi', which does not exist
WARNING: Makefile 'package/kernel/qca/qca-nss-clients/Makefile' has a dependency on 'kmod-qca-wifi', which does not exist
WARNING: Makefile 'package/kernel/qca/qca-nss-clients/Makefile' has a build dependency on 'kmod-qca-nss-crypto', which does not exist`

![image](https://user-images.githubusercontent.com/893941/220371476-0b3650dc-0276-4022-a61c-077ed60550ef.png)

**Comment by hzyitc** [comment]
Just warnings. Not need to care about them.

I just import some necessary modules from qsdk.

**Comment by PhoenixTrees** [comment]
> 
I want to install open clash but missing kmod-ipt-ipset
