### ISSUE TITLE
CR8808(CR8818?) ipq5018版本无法启动

### ISSUE THREAD

**Issue by baili233** [hzyitc/openwrt-redmi-ax3000#89]
尝试过5.15 5.4 4.4等版本均无法启动，报错如下图，貌似是找不到闪存
![0766c05f2813db38fb5ce7d699bb07e](https://github.com/user-attachments/assets/d7e0d5b3-3dfa-4f20-bacb-01da245a6a26)
而原版小米系统启动如下图
![a7cc839641da7eaae6e7950d0bde6b3](https://github.com/user-attachments/assets/b73f80bd-9745-43ab-b324-2c8960e40ecb)

**Comment by fecent** [comment]
刷的是哪个ubi，ax3000还是881x，要对版本刷

**Comment by baili233** [comment]
> 刷的是哪个ubi，ax3000还是881x，要对版本刷

刷的是881x，应该是没有添加我这个型号的NAND闪存，我自己添加（虽然不知道对不对）编译后成功启动了，
+   {"GD5F1GM7REYIG SPI NAND 1G 1.8V",
+       { .id = {0xc8, 0x81} },
+       SZ_2K, SZ_128, SZ_128K, 0, 2, 128, NAND_ECC_INFO(8, SZ_512) },
![5bcce1fa0591f29772ef5ea7068254b](https://github.com/user-attachments/assets/81a49fb3-857b-45df-9fea-090a0b3b2c5a)

**Comment by fecent** [comment]
感谢反馈，已安排跟进

**Comment by zeroneiko** [comment]
手上有一台2024.02生产的8818，遇到了和大佬一样的情况，请问大佬是通过修改哪一个patch文件实现适配的

**Comment by baili233** [comment]
> 手上有一台2024.02生产的8818，遇到了和大佬一样的情况，请问大佬是通过修改哪一个patch文件实现适配的

可以加个patch放到target/linux/ipq50xx/patches下

[422-add-GD5Fx-nand-support.patch](https://github.com/user-attachments/files/18519351/422-add-GD5Fx-nand-support.patch)

**Comment by zeroneiko** [comment]
感谢大佬相助！成功编译出GD5F1GM7REYIG NAND的8818可用的固件

**Comment by fecent** [comment]
- [ ] 8818遇刷后重启概率回到原系统，感觉像是crash之后触发failsafe类机制了，有可能是uboot不一样，待商讨

**Comment by baili233** [comment]
> * [ ]  8818遇刷后重启概率回到原系统，感觉像是crash之后触发failsafe类机制了，有可能是uboot不一样，待商讨

我也遇到了，所以我两个rootfs都刷了

**Comment by zeroneiko** [comment]
> > * [ ]   8818遇刷后重启概率回到原系统，感觉像是crash之后触发failsafe类机制了，有可能是uboot不一样，待商讨
> 
> 我也遇到了，所以我两个rootfs都刷了

手头有两台8818，一台23年一台24，实测用下来都有突然回滚系统的问题，初步推测不是自编译系统的问题

[openwrt-ipq50xx-arm-xiaomi_cr881x-squashfs-nand-factory.zip](https://github.com/user-attachments/files/18676850/openwrt-ipq50xx-arm-xiaomi_cr881x-squashfs-nand-factory.zip)

使用该魔改脚本刷写两个rootfs
```shell
# Check your partition table
# cat /proc/mtd
[[ "$(grep '"rootfs"' /proc/mtd | cut -d':' -f1)" == "mtd18" ]] || exit
[[ "$(grep '"rootfs_1"' /proc/mtd | cut -d':' -f1)" == "mtd19" ]] || exit

# Detect the current system slot and flash into the other one
# cat /proc/cmdline
mtd="$(grep -oE 'ubi.mtd=[a-zA-Z0-9\-\_]*' /proc/cmdline | cut -d'=' -f2)"
if [[ "$mtd" == "rootfs" ]]; then
    # Flash it as system 2
    ubiformat /dev/mtd19 -f openwrt-ipq50xx-arm-xiaomi_cr881x-squashfs-nand-factory.ubi
    #v2防回滚措施
    ubiformat /dev/mtd18 -f openwrt-ipq50xx-arm-xiaomi_cr881x-squashfs-nand-factory.ubi
    nvram set flag_try_sys2_failed=0
    nvram set flag_boot_rootfs=1
    nvram set flag_last_success=1
    nvram commit
elif [[ "$mtd" == "rootfs_1" ]]; then
    # Flash it as system 1
    ubiformat /dev/mtd18 -f openwrt-ipq50xx-arm-xiaomi_cr881x-squashfs-nand-factory.ubi
    #v2防回滚措施
    ubiformat /dev/mtd19 -f openwrt-ipq50xx-arm-xiaomi_cr881x-squashfs-nand-factory.ubi
    nvram set flag_try_sys1_failed=0
    nvram set flag_boot_rootfs=0
    nvram set flag_last_success=0
    nvram commit
fi

# Reboot
reboot
```
感谢各位佬的指点，发在这里作此备忘

**Comment by fecent** [comment]
直接手动刷掉两个分区就行了
ubiformat /dev/mtd18 -f openwrt-ipq50xx-arm-xiaomi_cr881x-squashfs-nand-factory.ubi
ubiformat /dev/mtd19 -f openwrt-ipq50xx-arm-xiaomi_cr881x-squashfs-nand-factory.ubi

自动切换另一个分区的话可以试试在openwrt的/etc/rc.local添加：
`fw_setenv flag_try_sys1_failed 0`
`fw_setenv flag_try_sys2_failed 0`
(参考https://www.reddit.com/r/openwrt/comments/1fb5y5o/issues_with_xiaomi_ax3200_after_installing_openwrt/)
不过可能有风险，比如一直卡死无限重启，具体为何会触发failed还得排查，另外里面也提到可以去修改启动顺序，未测试谨慎操作
